# Generated by Django 2.2.5 on 2020-02-18 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 18, 16, 17, 3, 975771)),
        ),
    ]
