# Generated by Django 2.2.5 on 2020-02-20 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsform', '0006_auto_20200220_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 16, 40, 0, 562410)),
        ),
    ]
