# Generated by Django 2.2.5 on 2020-02-20 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsform', '0008_auto_20200220_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 17, 1, 3, 17630)),
        ),
    ]
